//! Comprehensive Trading Analysis Example
//!
//! This example demonstrates how to use multiple technical indicators
//! together for a complete trading analysis, simulating real-world usage.

use chrono::{DateTime, NaiveDateTime, TimeZone, Utc};
use nyxs_owl::trade_math::{
    forecasting::{ExponentialSmoothing, LinearRegression},
    moving_averages::{ExponentialMovingAverage, SimpleMovingAverage, VolumeWeightedMovingAverage},
    oscillators::{Macd, RelativeStrengthIndex, StochasticOscillator},
    volatility::{AverageTrueRange, BollingerBands, StandardDeviation},
    volume::{OnBalanceVolume, VolumePriceTrend, VolumeRateOfChange},
};
use std::fs::File;
use std::io::{BufReader, Write};

/// Represents a market data point with full OHLCV data
#[derive(Debug, Clone)]
struct MarketData {
    timestamp: DateTime<Utc>,
    open: f64,
    high: f64,
    low: f64,
    close: f64,
    volume: f64,
}

/// Trading signal generated by our analysis
#[derive(Debug, Clone, PartialEq)]
enum TradingSignal {
    StrongBuy,
    Buy,
    Hold,
    Sell,
    StrongSell,
}

/// Complete technical analysis results for a data point
#[derive(Debug)]
struct TechnicalAnalysis {
    timestamp: DateTime<Utc>,
    price: f64,

    // Moving Averages
    sma_20: Option<f64>,
    ema_12: Option<f64>,
    ema_26: Option<f64>,
    vwma_20: Option<f64>,

    // Volatility
    bb_upper: Option<f64>,
    bb_middle: Option<f64>,
    bb_lower: Option<f64>,
    atr: Option<f64>,
    volatility: Option<f64>,

    // Oscillators
    rsi: Option<f64>,
    macd_line: Option<f64>,
    macd_signal: Option<f64>,
    macd_histogram: Option<f64>,
    stoch_k: Option<f64>,
    stoch_d: Option<f64>,

    // Volume
    obv: Option<f64>,
    vpt: Option<f64>,
    vroc: Option<f64>,

    // Forecasting
    price_forecast: Option<f64>,
    trend_strength: Option<f64>,

    // Final Signal
    signal: TradingSignal,
    confidence: f64,
}

/// Main technical analysis engine
struct TechnicalAnalysisEngine {
    // Moving Averages
    sma_20: SimpleMovingAverage,
    ema_12: ExponentialMovingAverage,
    ema_26: ExponentialMovingAverage,
    vwma_20: VolumeWeightedMovingAverage,

    // Volatility
    bb_20: BollingerBands,
    atr_14: AverageTrueRange,
    volatility: StandardDeviation,

    // Oscillators
    rsi_14: RelativeStrengthIndex,
    macd: Macd,
    stoch: StochasticOscillator,

    // Volume
    obv: OnBalanceVolume,
    vpt: VolumePriceTrend,
    vroc_10: VolumeRateOfChange,

    // Forecasting
    price_forecast: LinearRegression,
    trend_forecast: ExponentialSmoothing,
}

impl TechnicalAnalysisEngine {
    fn new() -> Result<Self, Box<dyn std::error::Error>> {
        Ok(Self {
            // Moving Averages
            sma_20: SimpleMovingAverage::new(20)?,
            ema_12: ExponentialMovingAverage::new(12)?,
            ema_26: ExponentialMovingAverage::new(26)?,
            vwma_20: VolumeWeightedMovingAverage::new(20)?,

            // Volatility
            bb_20: BollingerBands::new(20, 2.0)?,
            atr_14: AverageTrueRange::new(14)?,
            volatility: StandardDeviation::new(20)?,

            // Oscillators
            rsi_14: RelativeStrengthIndex::new(14)?,
            macd: Macd::new(12, 26, 9)?,
            stoch: StochasticOscillator::new(14, 3)?,

            // Volume
            obv: OnBalanceVolume::new(),
            vpt: VolumePriceTrend::new(),
            vroc_10: VolumeRateOfChange::new(10)?,

            // Forecasting
            price_forecast: LinearRegression::new(20)?,
            trend_forecast: ExponentialSmoothing::new(0.3)?,
        })
    }

    fn process(
        &mut self,
        data: &MarketData,
    ) -> Result<TechnicalAnalysis, Box<dyn std::error::Error>> {
        // Update all indicators
        self.sma_20.update(data.close)?;
        self.ema_12.update(data.close)?;
        self.ema_26.update(data.close)?;
        self.vwma_20.update(data.close, data.volume)?;

        self.bb_20.update(data.close)?;
        self.atr_14.update(data.high, data.low, data.close)?;
        self.volatility.update(data.close)?;

        self.rsi_14.update(data.close)?;
        self.macd.update(data.close)?;
        self.stoch.update(data.high, data.low, data.close)?;

        self.obv.update(data.close, data.volume)?;
        self.vpt.update(data.close, data.volume)?;
        self.vroc_10.update(data.volume)?;

        self.price_forecast.update(data.close)?;

        // Calculate trend strength from price movement
        let trend_value = if let (Ok(ema12), Ok(ema26)) = (self.ema_12.value(), self.ema_26.value())
        {
            ((ema12 - ema26) / ema26 * 100.0).abs()
        } else {
            0.0
        };
        self.trend_forecast.update(trend_value)?;

        // Generate analysis
        let analysis = TechnicalAnalysis {
            timestamp: data.timestamp,
            price: data.close,

            // Moving Averages
            sma_20: self.sma_20.value().ok(),
            ema_12: self.ema_12.value().ok(),
            ema_26: self.ema_26.value().ok(),
            vwma_20: self.vwma_20.value().ok(),

            // Volatility
            bb_upper: self.bb_20.upper_band().ok(),
            bb_middle: self.bb_20.middle_band().ok(),
            bb_lower: self.bb_20.lower_band().ok(),
            atr: self.atr_14.value().ok(),
            volatility: self.volatility.value().ok(),

            // Oscillators
            rsi: self.rsi_14.value().ok(),
            macd_line: self.macd.macd_value().ok(),
            macd_signal: self.macd.signal_value().ok(),
            macd_histogram: self.macd.histogram().ok(),
            stoch_k: self.stoch.k_value().ok(),
            stoch_d: self.stoch.d_value().ok(),

            // Volume
            obv: self.obv.value().ok(),
            vpt: self.vpt.value().ok(),
            vroc: self.vroc_10.value().ok(),

            // Forecasting
            price_forecast: self.price_forecast.forecast(1).ok(),
            trend_strength: self.trend_forecast.value().ok(),

            // Signal will be calculated
            signal: TradingSignal::Hold,
            confidence: 0.0,
        };

        // Generate trading signal
        let (signal, confidence) = self.generate_signal(&analysis);

        Ok(TechnicalAnalysis {
            signal,
            confidence,
            ..analysis
        })
    }

    fn generate_signal(&self, analysis: &TechnicalAnalysis) -> (TradingSignal, f64) {
        let mut bullish_signals = 0;
        let mut bearish_signals = 0;
        let mut total_signals = 0;
        let mut confidence_score = 0.0;

        // Moving Average Analysis
        if let (Some(ema12), Some(ema26)) = (analysis.ema_12, analysis.ema_26) {
            total_signals += 1;
            if ema12 > ema26 {
                bullish_signals += 1;
                confidence_score += 0.15;
            } else {
                bearish_signals += 1;
                confidence_score += 0.15;
            }
        }

        // Price vs SMA
        if let Some(sma20) = analysis.sma_20 {
            total_signals += 1;
            if analysis.price > sma20 {
                bullish_signals += 1;
                confidence_score += 0.10;
            } else {
                bearish_signals += 1;
                confidence_score += 0.10;
            }
        }

        // RSI Analysis
        if let Some(rsi) = analysis.rsi {
            total_signals += 1;
            if rsi < 30.0 {
                bullish_signals += 1; // Oversold
                confidence_score += 0.20;
            } else if rsi > 70.0 {
                bearish_signals += 1; // Overbought
                confidence_score += 0.20;
            } else if rsi > 50.0 {
                bullish_signals += 1;
                confidence_score += 0.05;
            } else {
                bearish_signals += 1;
                confidence_score += 0.05;
            }
        }

        // MACD Analysis
        if let (Some(macd_line), Some(macd_signal)) = (analysis.macd_line, analysis.macd_signal) {
            total_signals += 1;
            if macd_line > macd_signal {
                bullish_signals += 1;
                confidence_score += 0.15;
            } else {
                bearish_signals += 1;
                confidence_score += 0.15;
            }
        }

        // Bollinger Bands Analysis
        if let (Some(bb_upper), Some(bb_lower)) = (analysis.bb_upper, analysis.bb_lower) {
            total_signals += 1;
            if analysis.price <= bb_lower {
                bullish_signals += 1; // Price at lower band
                confidence_score += 0.15;
            } else if analysis.price >= bb_upper {
                bearish_signals += 1; // Price at upper band
                confidence_score += 0.15;
            }
        }

        // Volume Analysis (OBV trend)
        if let Some(_obv) = analysis.obv {
            // In a real implementation, we'd track OBV trend
            // For this example, we'll assume neutral
            total_signals += 1;
        }

        // Stochastic Analysis
        if let (Some(stoch_k), Some(stoch_d)) = (analysis.stoch_k, analysis.stoch_d) {
            total_signals += 1;
            if stoch_k < 20.0 && stoch_d < 20.0 {
                bullish_signals += 1; // Oversold
                confidence_score += 0.10;
            } else if stoch_k > 80.0 && stoch_d > 80.0 {
                bearish_signals += 1; // Overbought
                confidence_score += 0.10;
            }
        }

        // Calculate final signal
        let bullish_ratio = bullish_signals as f64 / total_signals as f64;
        let final_confidence = confidence_score / total_signals as f64;

        let signal = if bullish_ratio >= 0.7 {
            if final_confidence > 0.15 {
                TradingSignal::StrongBuy
            } else {
                TradingSignal::Buy
            }
        } else if bullish_ratio <= 0.3 {
            if final_confidence > 0.15 {
                TradingSignal::StrongSell
            } else {
                TradingSignal::Sell
            }
        } else {
            TradingSignal::Hold
        };

        (signal, final_confidence)
    }
}

/// Generate sample market data for demonstration
fn generate_sample_data() -> Vec<MarketData> {
    let mut data = Vec::new();
    let start_time = Utc::now() - chrono::Duration::days(100);
    let mut price = 100.0;

    for i in 0..100 {
        let timestamp = start_time + chrono::Duration::days(i);

        // Simulate realistic price movement
        let trend = (i as f64 * 0.1).sin() * 0.02;
        let noise = ((i * 17) % 100) as f64 / 100.0 - 0.5;
        let price_change = trend + noise * 0.01;

        price *= 1.0 + price_change;

        let open = price * (1.0 + ((i * 23) % 100) as f64 / 10000.0 - 0.005);
        let high = price * (1.0 + ((i * 31) % 50) as f64 / 10000.0 + 0.001);
        let low = price * (1.0 - ((i * 37) % 50) as f64 / 10000.0 - 0.001);
        let volume = 1000.0 + ((i * 41) % 5000) as f64;

        data.push(MarketData {
            timestamp,
            open,
            high,
            low,
            close: price,
            volume,
        });
    }

    data
}

/// Export analysis results to CSV
fn export_to_csv(
    results: &[TechnicalAnalysis],
    filename: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut file = File::create(filename)?;

    // Write CSV header
    writeln!(file, "timestamp,price,sma_20,ema_12,ema_26,rsi,macd_line,macd_signal,bb_upper,bb_lower,obv,signal,confidence")?;

    // Write data
    for result in results {
        writeln!(
            file,
            "{},{:.4},{},{},{},{},{},{},{},{},{},{:?},{:.4}",
            result.timestamp.format("%Y-%m-%d %H:%M:%S"),
            result.price,
            result
                .sma_20
                .map(|v| format!("{:.4}", v))
                .unwrap_or_else(|| "".to_string()),
            result
                .ema_12
                .map(|v| format!("{:.4}", v))
                .unwrap_or_else(|| "".to_string()),
            result
                .ema_26
                .map(|v| format!("{:.4}", v))
                .unwrap_or_else(|| "".to_string()),
            result
                .rsi
                .map(|v| format!("{:.2}", v))
                .unwrap_or_else(|| "".to_string()),
            result
                .macd_line
                .map(|v| format!("{:.4}", v))
                .unwrap_or_else(|| "".to_string()),
            result
                .macd_signal
                .map(|v| format!("{:.4}", v))
                .unwrap_or_else(|| "".to_string()),
            result
                .bb_upper
                .map(|v| format!("{:.4}", v))
                .unwrap_or_else(|| "".to_string()),
            result
                .bb_lower
                .map(|v| format!("{:.4}", v))
                .unwrap_or_else(|| "".to_string()),
            result
                .obv
                .map(|v| format!("{:.0}", v))
                .unwrap_or_else(|| "".to_string()),
            result.signal,
            result.confidence
        )?;
    }

    println!("Results exported to {}", filename);
    Ok(())
}

/// Print summary statistics
fn print_summary(results: &[TechnicalAnalysis]) {
    let mut buy_signals = 0;
    let mut sell_signals = 0;
    let mut hold_signals = 0;
    let mut total_confidence = 0.0;

    for result in results {
        match result.signal {
            TradingSignal::StrongBuy | TradingSignal::Buy => buy_signals += 1,
            TradingSignal::StrongSell | TradingSignal::Sell => sell_signals += 1,
            TradingSignal::Hold => hold_signals += 1,
        }
        total_confidence += result.confidence;
    }

    let avg_confidence = total_confidence / results.len() as f64;

    println!("\n=== ANALYSIS SUMMARY ===");
    println!("Total data points: {}", results.len());
    println!(
        "Buy signals: {} ({:.1}%)",
        buy_signals,
        buy_signals as f64 / results.len() as f64 * 100.0
    );
    println!(
        "Sell signals: {} ({:.1}%)",
        sell_signals,
        sell_signals as f64 / results.len() as f64 * 100.0
    );
    println!(
        "Hold signals: {} ({:.1}%)",
        hold_signals,
        hold_signals as f64 / results.len() as f64 * 100.0
    );
    println!("Average confidence: {:.3}", avg_confidence);

    if let (Some(first), Some(last)) = (results.first(), results.last()) {
        let price_change = (last.price - first.price) / first.price * 100.0;
        println!(
            "Price change: {:.2}% (from {:.2} to {:.2})",
            price_change, first.price, last.price
        );
    }
}

/// Display recent signals
fn display_recent_signals(results: &[TechnicalAnalysis], count: usize) {
    println!("\n=== RECENT SIGNALS ===");
    let recent: Vec<_> = results.iter().rev().take(count).collect();

    for result in recent.iter().rev() {
        println!(
            "{} | Price: {:8.2} | {:>10?} | Confidence: {:.3} | RSI: {} | MACD: {}",
            result.timestamp.format("%Y-%m-%d"),
            result.price,
            result.signal,
            result.confidence,
            result
                .rsi
                .map(|v| format!("{:5.1}", v))
                .unwrap_or_else(|| "  N/A".to_string()),
            if let (Some(macd), Some(signal)) = (result.macd_line, result.macd_signal) {
                if macd > signal {
                    "Bullish"
                } else {
                    "Bearish"
                }
            } else {
                "N/A"
            }
        );
    }
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("🦉 NyxsOwl Comprehensive Trading Analysis 🦉\n");

    // Initialize the analysis engine
    let mut engine = TechnicalAnalysisEngine::new()?;
    println!("✅ Technical analysis engine initialized");

    // Generate sample market data
    let market_data = generate_sample_data();
    println!(
        "✅ Generated {} days of sample market data",
        market_data.len()
    );

    // Process all data through the analysis engine
    let mut results = Vec::new();
    for (i, data) in market_data.iter().enumerate() {
        match engine.process(data) {
            Ok(analysis) => results.push(analysis),
            Err(e) => {
                eprintln!("Error processing data point {}: {}", i, e);
                continue;
            }
        }
    }

    println!("✅ Processed {} data points successfully", results.len());

    // Display results
    print_summary(&results);
    display_recent_signals(&results, 10);

    // Export results
    export_to_csv(&results, "trading_analysis.csv")?;

    // Demonstrate real-time analysis
    println!("\n=== REAL-TIME ANALYSIS DEMO ===");
    if let Some(latest_data) = market_data.last() {
        // Simulate new data point
        let mut new_data = latest_data.clone();
        new_data.timestamp = Utc::now();
        new_data.close *= 1.01; // 1% price increase
        new_data.volume *= 1.2; // 20% volume increase

        let analysis = engine.process(&new_data)?;
        println!("New data processed:");
        println!(
            "  Price: {:.2} -> {:.2} (+{:.2}%)",
            latest_data.close,
            new_data.close,
            (new_data.close - latest_data.close) / latest_data.close * 100.0
        );
        println!(
            "  Signal: {:?} (confidence: {:.3})",
            analysis.signal, analysis.confidence
        );

        if let Some(rsi) = analysis.rsi {
            println!(
                "  RSI: {:.1} {}",
                rsi,
                if rsi > 70.0 {
                    "(Overbought)"
                } else if rsi < 30.0 {
                    "(Oversold)"
                } else {
                    "(Normal)"
                }
            );
        }

        if let (Some(bb_upper), Some(bb_lower)) = (analysis.bb_upper, analysis.bb_lower) {
            let bb_position = (analysis.price - bb_lower) / (bb_upper - bb_lower);
            println!(
                "  Bollinger Band Position: {:.1}% {}",
                bb_position * 100.0,
                if bb_position > 0.8 {
                    "(Near upper band)"
                } else if bb_position < 0.2 {
                    "(Near lower band)"
                } else {
                    "(Middle range)"
                }
            );
        }
    }

    println!("\n🎉 Analysis complete! Check 'trading_analysis.csv' for detailed results.");

    Ok(())
}
